model_args:
  model_name: resnet18
  resolution: 224
  embed_model_weights: ResNet18_Weights.DEFAULT
  distributed: True

dataset_args:
  dataset_name: ImageNet
  normalize: True
  singular_embed: True

backdoor_args:
  mark_width: 8
  poison_num: 5000
  backdoor_name: binary-map
  target_class: -1 # make target class -1 so sampling is done from all classes
  num_triggers: 30
  num_target_classes: 1000
  prepared: True

defense_args:
  def_name: neural-cleanse
  def_opt: sgd
  def_eval_every: 50
  def_data_ratio: 0.025
  def_init_lr: 0.001
  nc_steps_removal: 1_000
  nc_lambda_norm: 0.02
  nc_trigger_norm: 1
  nc_accelerate_target: 0
  nc_boost_backdoor: 1
  nc_poison_num: 100
  nc_steps_per_class: 100
  def_num_steps: 1000
  nc_show_backdoor: False

backdoored_model_args:
  bdma_verbose: False
  model_file: resnet18.pt
  backdoor_file: backdoor.bd
  path: /home/b3schnei/experiments/lda_backdoor_90/

env_args:
  batch_size: 128
  num_workers: 4
  num_validation_workers: 2
  gpus: [3]
  port: 3009

output_dir:
  name: lda_backdoor_5k
  root: /home/b3schnei/experiments/
  wandb_project: 'universal_backdoor_project'
  iterations_per_log: 4000
  sample_size: 20000
  checkpoint_every_n_epochs: 10
  notes: "fresh training 5k samples"

