model_args:
  model_name: resnet18
  #model_ckpt: /home/nlukas/certified-robustness/observers/cifar_badnet_clean_00009/best.pt
  resolution: 224
  base_model_weights: ResNet18_Weights.DEFAULT

dataset_args:
  dataset_name: ImageNet
  #dataset_name: CIFAR10
  normalize: True

env_args:
  batch_size: 128
