model_args:
  model_name: resnet18
  #model_ckpt: /home/nlukas/certified-robustness/observers/cifar_badnet_clean_00009/best.pt
  resolution: 224
  base_model_weights: ResNet18_Weights.DEFAULT

dataset_args:
  dataset_name: ImageNet
  #dataset_name: CIFAR10
  normalize: True

backdoor_args:
  mark_width: 10
  poison_num: 200000
  backdoor_name: binary-map
  target_class: -1
  num_triggers: 20
  num_target_classes: 1000

env_args:
  batch_size: 128
  num_workers: 4

trainer_args:
  epochs: 5
  save_only_best: False     # save every model
  momentum: 0.9
  lr: 0.0001
  weight_decay: 0.0001
  cosine_annealing_scheduler: False
  t_max: 30

