model_args:
  model_name: resnet18
  resolution: 224
  base_model_weights: ResNet18_Weights.DEFAULT

dataset_args:
  dataset_name: ImageNet
  normalize: True

backdoor_args:
  mark_width: 10
  poison_num: 75000
  backdoor_name: binary-map
  target_class: -1 # make target class -1 so sampling is done from all classes
  num_triggers: 20
  num_target_classes: 1000

env_args:
  batch_size: 128
  num_workers: 4

trainer_args:
  epochs: 0
  save_only_best: False     # save every model
  momentum: 0.9
  lr: 0.0001
  weight_decay: 0.0001
  cosine_annealing_scheduler: False
  t_max: 30

output_dir:
  name: latent_direction_poison
  root: /home/b3schnei/experiments/
  notes: "100K poisons, 20 triggers, 5 epochs, Expect about ~80% ASR, config for embed_binary_universal_backdoor.py"

