model_args:
  model_name: resnet18
  resolution: 224
  base_model_weights: ResNet18_Weights.DEFAULT

dataset_args:
  dataset_name: ImageNet
  normalize: True
  singular_embed: True

backdoor_args:
  mark_width: 8
  num_triggers: 30
  poison_num: 1000
  backdoor_name: multi-badnets
  target_class: -1 # make target class -1 so sampling is done from all classes
  num_target_classes: 1000
  image_dimension: 224
  prepared: True

env_args:
  batch_size: 128
  num_workers: 1

trainer_args:
  epochs: 25
  save_only_best: False     # save every model
  momentum: 0.9
  lr: 0.0001
  weight_decay: 0.0001
  cosine_annealing_scheduler: False
  t_max: 30

output_dir:
  name: mbn_backdoor
  root: /home/b3schnei/experiments/
  wandb_project: 'universal_backdoor_project'
  iterations_per_log: 5
  sample_size: 500
  notes: ""

