model_args:
  model_name: resnet18
  resolution: 224
  embed_model_weights: ResNet18_Weights.DEFAULT
  distributed: True

dataset_args:
  dataset_name: ImageNet
  normalize: True

backdoor_args:
  mark_width: 8
  poison_num: 10
  backdoor_name: binary-map
  target_class: -1 # make target class -1 so sampling is done from all classes
  num_triggers: 30
  num_target_classes: 1000

env_args:
  batch_size: 128
  num_workers: 8
  gpus: [1,2]

trainer_args:
  epochs: 50
  save_only_best: False     # save every model
  momentum: 0.9
  lr: 0.0001
  weight_decay: 0.0001
  cosine_annealing_scheduler: False
  t_max: 30

output_dir:
  name: lda_backdoor
  root: /home/b3schnei/experiments/
  wandb_project: 'universal_backdoor_project'
  iterations_per_log: 2503
  sample_size: 1000
  notes: ""

